plugins {
    id 'java'
    id 'application'
    id 'checkstyle'
}

group = 'com.aspose.barcode.java.example'
version = '25.9.0'

ext {
    javaTarget = JavaVersion.VERSION_17
    junitVersion = '5.10.3'
}

repositories {
    maven {
        url "https://releases.aspose.com/java/repo/"
    }
    mavenCentral()
}

java {
    sourceCompatibility = javaTarget
    targetCompatibility = javaTarget
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

test {
    useTestNG()
}

dependencies {
    implementation 'com.aspose:aspose-barcode:25.9'
    testImplementation 'com.aspose:aspose-barcode:25.9'
    testImplementation 'org.testng:testng:7.10.2'
}